# Package Overview
package_name: src

# Data Files for Training and Testing
app_config:
  data_file: datasets/data.csv
  save_model_directory: 'trained_models'
# Model Configuration
mode_config:
  model_name: 'loan_approval_classifier.pkl'
  pipeline_name: 'loan_approval_pipeline.pkl'
  file_extension: '.pkl'
  n_neighbors: 5
  test_size: 0.2
  random_state: 42
# Feature Configuration
features:
  num_vars:
    - CoBorrowerTotalMonthlyIncome
    - CoBorrowerAge
    - CoBorrowerYearsInSchool
    - BorrowerTotalMonthlyIncome
    - BorrowerAge
    - DTI
    - CLTV
    - CreditScore
    - TotalLoanAmount
    - Approved
  cat_vars:
    - LeadSourceGroup
    - Group
    - LoanPurpose
  unused_fields:
    - Approved


